### ISSUE TITLE
[ERROR] Check if the Menti-ID is valid

### ISSUE THREAD

**Issue by fajrulfx** [Primexz/Menti_Spammer-Py#1]
I got this error when using the program, even though I submit the valid Menti-ID.
- Device: Windows 10
- Python version: 3.9.4

```
[INFO] Prepared Wordlist (50000 words)
[ERROR] There was an error on requesting informations from Menti!

Check if the Menti-ID is valid!
```

**Comment by Primexz** [comment]
Checked this repo.
Seems to work still..
